### ISSUE TITLE
辞書生成の際に浜松市中央区（2024.1.1から施行）の処理ができずクラッシュする

### ISSUE THREAD

**Issue by kamataryo** [t-sagara/jageocoder-converter#7]
こんにちは、辞書の生成を試したところ、 郵便局データの処理中にクラッシュする現象に遭遇しましたので報告させていただきます。
`PostCoder` の Converter の処理で、市区町村コード 22138 （浜松市中央区、2024.1.1から施行）に遭遇し、エラーとなっているようです。

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/kamataryo/Desktop/rits/jageocoder-converter/jageocoder_converter/__main__.py", line 109, in <module>
    db_dir = jageocoder_converter.convert(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kamataryo/Desktop/rits/jageocoder-converter/jageocoder_converter/__init__.py", line 197, in convert
    __prepare_postcoder(os.path.join(download_dir, 'japanpost'))
  File "/Users/kamataryo/Desktop/rits/jageocoder-converter/jageocoder_converter/__init__.py", line 43, in __prepare_postcoder
    postcoder = PostCoder.get_instance(directory)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kamataryo/Desktop/rits/jageocoder-converter/jageocoder_converter/postcoder.py", line 264, in get_instance
    cls.postcoder.load_file()
  File "/Users/kamataryo/Desktop/rits/jageocoder-converter/jageocoder_converter/postcoder.py", line 81, in load_file
    x[1] for x in self.jiscodes[citycode]])
                  ~~~~~~~~~~~~~^^^^^^^^^^
KeyError: '22138'
```

**Comment by t-sagara** [comment]
市区町村コードの対応表は  https://geonlp.ex.nii.ac.jp/dictionary/geoshape-city/geoshape-city-geolod.csv から
ダウンロードしているのですが、まだ浜松市中央区・浜名区・天竜区が反映されていません。
エラーが出た場合、ダウンロード済みの geoshape-city-geolod.csv (download/geonlp/geoshape-city-geolod.csv) に
以下の三行を追加して、もう一度実行してみてください。

```
CeCGij,22138A2024,中央,中央,区/,静岡県,静岡県,浜松市,浜松市,市区町村,静岡県/浜松市,34.71086500,137.72611700,静岡県浜松市中央区,22138,2024-01-01,,1/浜松市中央区役所/浜松市中央区元城町103-2/P34-14_22.xml,https://geoshape.ex.nii.ac.jp/city/resource/22138A2024.html
RscWYQ,22139A2024,浜名,浜名,区/,静岡県,静岡県,浜松市,浜松市,市区町村,静岡県/浜松市,34.79328000,137.78999400,静岡県浜松市浜名区,22139,2024-04-01,,1/浜松市浜名区役所/浜松市浜名区西美薗6/P34-14_22.xml,https://geoshape.ex.nii.ac.jp/city/resource/22139A2024.html
UkkcUy,22140A2024,天竜,天竜,区/,静岡県,静岡県,浜松市,浜松市,市区町村,静岡県/浜松市,34.87268600,137.81592400,静岡県浜松市天竜区,22140,2024-04-01,,1/浜松市天竜区役所/浜松市天竜区二俣町二俣481/P34-14_22.xml,https://geoshape.ex.nii.ac.jp/city/resource/22140A2024.html
```
